apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
    path: kubernetes/overlays/dev/security
    targetRevision: readmev2
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true