apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KHDevOps/eks-scalable-devops-platform
    path: helm-charts/cluster-autoscaler
    targetRevision: readmev2
    helm:
      valueFiles:
        - ../../helm-values/dev/cluster-autoscaler/values.yaml
      parameters:
        - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::773398142927:role/eks-cluster-dev-cluster-autoscaler"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false