pipeline {
    agent { label 'built-in' }

    parameters {
        credentials(
            name: 'GIT_CREDENTIALS',
            description: 'Choose your credentials Git',
            credentialType: 'com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl',
            defaultValue: '',
            required: true
        )
    }

    stages {

        stage('Checkout Config Repo') {
            steps {
                git branch: 'main',
                    credentialsId: params.GIT_CREDENTIALS,
                    url: "https://github.com/KHDevOps/eks-scalable-devops-platform"
            }
        }

        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                script {
                    def config = readYaml file: 'templates/app-config.yaml'
                    def configRepo = config.git.config_repo
                    def defaultBranch = config.git.default_branch

                    writeFile file: 'hello-world.txt', text: """
Hello World from Jenkins!

Build Information:
- Build Number: ${BUILD_NUMBER}
- Job Name: ${JOB_NAME}
- Date: ${new Date()}
- Branch: ${defaultBranch}

This is a test deployment!
"""

                    sh('git config user.email "jenkins@yourproject.com"')
                    sh('git config user.name "Jenkins Automation"')
                    
                    withCredentials([usernamePassword(credentialsId: params.GIT_CREDENTIALS, passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh('git add hello-world.txt')
                        sh('git commit -m "Jenkins deployment"')
                        sh("git push https://\${GIT_USERNAME}:\${GIT_PASSWORD}@${configRepo} ${defaultBranch}")
                    }

                    echo "Hello World successfully deployed!"
                }
            }
        }
    }
}